#!/bin/sh

NAME="statisticscollector"
DESC="statisticscollector"

HOME="/home/vagrant"
ROOTDIR="$HOME/sites"
INSTALLDIR="$ROOTDIR/StatisticsCollector"
LIBS="$INSTALLDIR/local/lib/perl5:$INSTALLDIR/lib"

PERLDIR="$HOME/perl5/perlbrew/perls/perl-5.14.2"
STARMAN="$INSTALLDIR/local/bin/starman"
PID="$ROOTDIR/pid/$NAME.pid"
PORT="127.0.0.1:5000"
OPTS="--listen $PORT --pid $PID --daemonize --user vagrant --group vagrant"
PSGI="$INSTALLDIR/statisticscollector.psgi"

STATISTICSCOLLECTOR_CONFIG="$INSTALLDIR/config"
STATISTICSCOLLECTOR_CONFIG_LOCAL_SUFFIX="dev"

case "$1" in
    start)
        echo -n "Starting $DESC: "
        PERL5LIB=$LIBS $STARMAN $OPTS $PSGI
        echo "$NAME."
        ;;

    stop)
        echo -n "Stopping $DESC: "
        kill `cat $PID`
        echo "$NAME."
        ;;

    restart)
        echo -n "Restarting $DESC: "
        kill `cat $PID`
        sleep 1
        PERL5LIB=$LIBS $STARMAN $OPTS $PSGI
        echo "$NAME."
        ;;

    status)
        if [ -f $PID ] ; then 
            echo "$NAME is running."
        else
            echo "$NAME is not running."
        fi
        ;;

    *)
        echo "Usage: $NAME { start | stop | restart | status }"
        exit 1
        ;;
esac
