#!/bin/sh

NAME="[% name %]"
LIBS="[% app_dir %]/local/lib/perl5"
OPTS="--listen 127.0.0.1:[% port %] --pid [% pid %] --daemonize --user [% user %] --group [% group %]"

case "$1" in
    start)
        echo -n "Starting $NAME: "
        PERL5LIB=$LIBS [% starman %] $OPTS [% psgi %]
        echo "$NAME."
        ;;

    stop)
        echo -n "Stopping $NAME: "
        kill `cat [% pid %]`
        echo "$NAME."
        ;;

    restart)
        echo -n "Restarting $NAME: "
        kill `cat [% pid %]`
        sleep 1
        PERL5LIB=$LIBS [% starman %] $OPTS [% psgi %]
        echo "$NAME."
        ;;

    status)
        if [ -f [% pid %] ] ; then 
            echo "$NAME is running."
        else
            echo "$NAME is not running."
        fi
        ;;

    *)
        echo "Usage: $NAME { start | stop | restart | status }"
        exit 1
        ;;
esac
